// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bind_udp_reuse`, `extract_tag`, `is_own_source`, `local_ipv4_set`, `now_unix_ms`, `parse_lan_payload`, `parse_minecraft_motd`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LAN_DISCOVERIES`, `LAN_LISTENERS`, `LanGameListener`, `MULTICAST_RT`, `MULTICAST_SENDERS`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `deref`, `deref`, `deref`, `initialize`, `initialize`, `initialize`, `initialize`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`, `with_bind_addr`

/// 创建并启动一个组播发送器
/// 返回发送器索引，用于后续操作
Future<BigInt> createMulticastSender({
  required String multicastAddr,
  required int port,
  required List<int> data,
  required BigInt intervalMs,
}) => RustLib.instance.api.crateApiMulticastCreateMulticastSender(
  multicastAddr: multicastAddr,
  port: port,
  data: data,
  intervalMs: intervalMs,
);

/// 创建并启动一个组播发送器（带自定义绑定地址）
Future<BigInt> createMulticastSenderWithBind({
  required String multicastAddr,
  required int port,
  required String bindAddr,
  required List<int> data,
  required BigInt intervalMs,
}) => RustLib.instance.api.crateApiMulticastCreateMulticastSenderWithBind(
  multicastAddr: multicastAddr,
  port: port,
  bindAddr: bindAddr,
  data: data,
  intervalMs: intervalMs,
);

/// 停止指定索引的组播发送器
Future<void> stopMulticastSender({required BigInt index}) =>
    RustLib.instance.api.crateApiMulticastStopMulticastSender(index: index);

/// 停止所有组播发送器
Future<void> stopAllMulticastSenders() =>
    RustLib.instance.api.crateApiMulticastStopAllMulticastSenders();

/// 获取所有正在运行的组播发送器数量
Future<BigInt> getMulticastSenderCount() =>
    RustLib.instance.api.crateApiMulticastGetMulticastSenderCount();

/// 检查指定发送器是否正在运行
Future<bool> isMulticastSenderRunning({required BigInt index}) => RustLib
    .instance
    .api
    .crateApiMulticastIsMulticastSenderRunning(index: index);

/// 启动通用 UDP 组播监听；`parser` 决定如何从载荷提取游戏端口。
///
/// 已知 parser：`minecraft_motd`。仅收录本机网卡/回环来源。
Future<BigInt> startUdpMulticastLanListener({
  required String multicastAddr,
  required int port,
  required String parser,
}) => RustLib.instance.api.crateApiMulticastStartUdpMulticastLanListener(
  multicastAddr: multicastAddr,
  port: port,
  parser: parser,
);

/// 兼容旧名：MC MOTD 组播监听。
Future<BigInt> startMinecraftLanListener({
  required String multicastAddr,
  required int port,
}) => RustLib.instance.api.crateApiMulticastStartMinecraftLanListener(
  multicastAddr: multicastAddr,
  port: port,
);

/// 拉取当前发现到的本机开放游戏（自动丢掉 20s 未再见的条目）。
Future<List<LanGameDiscovery>> pollLanGameDiscoveries() =>
    RustLib.instance.api.crateApiMulticastPollLanGameDiscoveries();

/// 停止所有局域网组播监听并清空发现缓存。
Future<void> stopAllLanGameListeners() =>
    RustLib.instance.api.crateApiMulticastStopAllLanGameListeners();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MulticastSender>>
abstract class MulticastSender implements RustOpaqueInterface {
  Future<bool> isRunning();

  Future<void> start();

  Future<void> stop();
}

/// 组播/解析得到的本机开放游戏（与具体游戏解耦）。
class LanGameDiscovery {
  /// 解析器名，如 `minecraft_motd`。
  final String parser;
  final int gamePort;
  final String motd;
  final String sourceIp;
  final BigInt seenUnixMs;

  const LanGameDiscovery({
    required this.parser,
    required this.gamePort,
    required this.motd,
    required this.sourceIp,
    required this.seenUnixMs,
  });

  @override
  int get hashCode =>
      parser.hashCode ^
      gamePort.hashCode ^
      motd.hashCode ^
      sourceIp.hashCode ^
      seenUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LanGameDiscovery &&
          runtimeType == other.runtimeType &&
          parser == other.parser &&
          gamePort == other.gamePort &&
          motd == other.motd &&
          sourceIp == other.sourceIp &&
          seenUnixMs == other.seenUnixMs;
}
