// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collect_relay_hops`, `emit_core_log`, `ensure_runtime`, `event_to_message`, `get_instance_info`, `lookup_app_rpc_ready`, `lookup_app_rpc`, `parse_instance_id`, `peer_conn_info_to_string`, `spawn_event_forwarder`, `spawn_instance_event_forwarder`, `tracing_log_lagged`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CORE_LOG_SINK`, `MANAGER`, `RT`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `deref`, `deref`, `deref`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `initialize`, `initialize`, `initialize`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `network_status_from_info`, `peer_route_pairs_from_info`

/// Dart 侧订阅内核日志流；后订阅覆盖前订阅。
Stream<CoreLogEventC> subscribeCoreLogs() =>
    RustLib.instance.api.crateApiP2PSubscribeCoreLogs();

Future<String> easytierVersion() =>
    RustLib.instance.api.crateApiP2PEasytierVersion();

Future<bool> isEasytierRunning({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PIsEasytierRunning(instanceId: instanceId);

Future<void> setTunFd({required String instanceId, required int fd}) =>
    RustLib.instance.api.crateApiP2PSetTunFd(instanceId: instanceId, fd: fd);

Future<String> createInstance({
  required String configToml,
  required bool watchEvent,
}) => RustLib.instance.api.crateApiP2PCreateInstance(
  configToml: configToml,
  watchEvent: watchEvent,
);

Future<void> closeInstance({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PCloseInstance(instanceId: instanceId);

Future<KVNetworkStatus> getNetworkStatus({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PGetNetworkStatus(instanceId: instanceId);

/// Send a request-response RPC to `dst_peer_id` and await the typed reply.
///
/// 不要用 `RT.spawn(...).await` 把这次调用搬到 `RT` —— `RT` 既不是 FRB 的
/// runtime，也不是 EasyTier 每个 instance 自己的 runtime（见 `EasyTierLauncher::start`
/// 里的 `std::thread::spawn` + 独立 `tokio::runtime::Runtime`）。跨三个 runtime
/// 调度时，`tokio::time::timeout` 注册在 RT 的 timer driver、mpsc 唤醒发生在
/// EasyTier runtime、JoinHandle 唤醒落在 FRB executor，时序上很容易错过 wake，
/// 表现为 Dart 侧 `appCall` 永久 Pending、5s 超时也不触发。直接在 FRB executor
/// 上 `.await svc.call()` 反而是稳的（参考 commit a0fb25e）。
Future<AppCallResultC> appCall({
  required String instanceId,
  required int dstPeerId,
  required String channel,
  required BigInt requestId,
  required List<int> payload,
  required int flags,
  required int timeoutMs,
}) => RustLib.instance.api.crateApiP2PAppCall(
  instanceId: instanceId,
  dstPeerId: dstPeerId,
  channel: channel,
  requestId: requestId,
  payload: payload,
  flags: flags,
  timeoutMs: timeoutMs,
);

/// Send a fire-and-forget notification to `dst_peer_id`. The RPC ack is still
/// awaited so the caller can detect routing failures within `timeout_ms`.
Future<void> appNotify({
  required String instanceId,
  required int dstPeerId,
  required String channel,
  required List<int> payload,
  required int timeoutMs,
}) => RustLib.instance.api.crateApiP2PAppNotify(
  instanceId: instanceId,
  dstPeerId: dstPeerId,
  channel: channel,
  payload: payload,
  timeoutMs: timeoutMs,
);

/// Round-trip ping. Returns the measured RTT in milliseconds.
Future<PlatformInt64> peerPing({
  required String instanceId,
  required int dstPeerId,
  required int timeoutMs,
}) => RustLib.instance.api.crateApiP2PPeerPing(
  instanceId: instanceId,
  dstPeerId: dstPeerId,
  timeoutMs: timeoutMs,
);

/// Stream inbound `Call` and `Notify` events from a running instance into
/// Dart. The future resolves once the EasyTier instance shuts down (the
/// underlying broadcast channel is closed); Dart can re-subscribe after a
/// subsequent `create_instance` call.
Stream<AppInboundEventC> subscribeAppInbound({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PSubscribeAppInbound(instanceId: instanceId);

/// Reply to an inbound `Call` identified by `token`. Returns `true` if the
/// reply was delivered to the awaiting RPC task, `false` if the token was
/// already replied to / timed out / never existed.
///
/// `status == 0` is convention for "ok"; positive values are application
/// defined; negative values are reserved for transport-level codes (see
/// [`app_rpc_status`]).
Future<bool> appCallReply({
  required String instanceId,
  required BigInt token,
  required int status,
  required String errorMsg,
  required List<int> payload,
}) => RustLib.instance.api.crateApiP2PAppCallReply(
  instanceId: instanceId,
  token: token,
  status: status,
  errorMsg: errorMsg,
  payload: payload,
);

/// Local peer id for the given instance, exposed so Dart can label outgoing
/// traffic (the EasyTier route table uses the same `peer_id` space).
Future<int> myPeerId({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PMyPeerId(instanceId: instanceId);

/// Result of [`app_call`] — directly maps `AppCallResponse` to a Dart record.
class AppCallResultC {
  final int status;
  final String errorMsg;
  final Uint8List payload;

  const AppCallResultC({
    required this.status,
    required this.errorMsg,
    required this.payload,
  });

  @override
  int get hashCode => status.hashCode ^ errorMsg.hashCode ^ payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppCallResultC &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          errorMsg == other.errorMsg &&
          payload == other.payload;
}

/// Inbound event delivered through [`subscribe_app_inbound`].
///
/// Modelled as a flat struct (rather than a Rust enum with payload variants)
/// so that the Dart binding stays a plain `dart class`, no `freezed` dep.
class AppInboundEventC {
  final AppInboundKindC kind;
  final int fromPeerId;
  final String channel;

  /// `request_id` echoed from the caller (0 for `Notify`).
  final BigInt requestId;

  /// Reply correlation token (0 for `Notify`). Pass to [`app_call_reply`].
  final BigInt token;
  final Uint8List payload;

  const AppInboundEventC({
    required this.kind,
    required this.fromPeerId,
    required this.channel,
    required this.requestId,
    required this.token,
    required this.payload,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      fromPeerId.hashCode ^
      channel.hashCode ^
      requestId.hashCode ^
      token.hashCode ^
      payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInboundEventC &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          fromPeerId == other.fromPeerId &&
          channel == other.channel &&
          requestId == other.requestId &&
          token == other.token &&
          payload == other.payload;
}

/// Discriminator for [`AppInboundEventC`].
enum AppInboundKindC {
  /// Request expecting a reply. Receiver MUST call [`app_call_reply`] with
  /// the carried `token`, otherwise the remote caller observes
  /// `app_rpc_status::REPLY_TIMEOUT` after the receiver-side timeout
  /// (default 30s, configured in EasyTier).
  call,

  /// Fire-and-forget notification (the sender already received an RPC-layer
  /// ack; this event is informational on the receiver side). For `Notify`
  /// events `request_id` and `token` are always 0.
  notify,
}

/// EasyTier 内核日志事件（替代 UDP 127.0.0.1:9999）。
class CoreLogEventC {
  final String instanceId;
  final String message;

  const CoreLogEventC({required this.instanceId, required this.message});

  @override
  int get hashCode => instanceId.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreLogEventC &&
          runtimeType == other.runtimeType &&
          instanceId == other.instanceId &&
          message == other.message;
}

class KVNetworkStatus {
  final BigInt totalNodes;
  final List<KVNodeInfo> nodes;

  const KVNetworkStatus({required this.totalNodes, required this.nodes});

  @override
  int get hashCode => totalNodes.hashCode ^ nodes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KVNetworkStatus &&
          runtimeType == other.runtimeType &&
          totalNodes == other.totalNodes &&
          nodes == other.nodes;
}

class KVNodeConnectionStats {
  final String connType;
  final BigInt rxBytes;
  final BigInt txBytes;
  final BigInt rxPackets;
  final BigInt txPackets;

  const KVNodeConnectionStats({
    required this.connType,
    required this.rxBytes,
    required this.txBytes,
    required this.rxPackets,
    required this.txPackets,
  });

  @override
  int get hashCode =>
      connType.hashCode ^
      rxBytes.hashCode ^
      txBytes.hashCode ^
      rxPackets.hashCode ^
      txPackets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KVNodeConnectionStats &&
          runtimeType == other.runtimeType &&
          connType == other.connType &&
          rxBytes == other.rxBytes &&
          txBytes == other.txBytes &&
          rxPackets == other.rxPackets &&
          txPackets == other.txPackets;
}

class KVNodeInfo {
  final int peerId;
  final String hostname;
  final String ipv4;

  /// 虚拟网 IPv6（含前缀长度），与 `Route.ipv6_addr` 一致；无分配时为空串。
  final String ipv6;
  final double latencyMs;
  final String nat;
  final List<NodeHopStats> hops;
  final double lossRate;
  final List<KVNodeConnectionStats> connections;
  final String tunnelProto;
  final String connType;
  final BigInt rxBytes;
  final BigInt txBytes;
  final String version;
  final int cost;

  const KVNodeInfo({
    required this.peerId,
    required this.hostname,
    required this.ipv4,
    required this.ipv6,
    required this.latencyMs,
    required this.nat,
    required this.hops,
    required this.lossRate,
    required this.connections,
    required this.tunnelProto,
    required this.connType,
    required this.rxBytes,
    required this.txBytes,
    required this.version,
    required this.cost,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      hostname.hashCode ^
      ipv4.hashCode ^
      ipv6.hashCode ^
      latencyMs.hashCode ^
      nat.hashCode ^
      hops.hashCode ^
      lossRate.hashCode ^
      connections.hashCode ^
      tunnelProto.hashCode ^
      connType.hashCode ^
      rxBytes.hashCode ^
      txBytes.hashCode ^
      version.hashCode ^
      cost.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KVNodeInfo &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          hostname == other.hostname &&
          ipv4 == other.ipv4 &&
          ipv6 == other.ipv6 &&
          latencyMs == other.latencyMs &&
          nat == other.nat &&
          hops == other.hops &&
          lossRate == other.lossRate &&
          connections == other.connections &&
          tunnelProto == other.tunnelProto &&
          connType == other.connType &&
          rxBytes == other.rxBytes &&
          txBytes == other.txBytes &&
          version == other.version &&
          cost == other.cost;
}

class NodeHopStats {
  final int peerId;
  final String targetIp;
  final double latencyMs;
  final double packetLoss;
  final String nodeName;

  const NodeHopStats({
    required this.peerId,
    required this.targetIp,
    required this.latencyMs,
    required this.packetLoss,
    required this.nodeName,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      targetIp.hashCode ^
      latencyMs.hashCode ^
      packetLoss.hashCode ^
      nodeName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NodeHopStats &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          targetIp == other.targetIp &&
          latencyMs == other.latencyMs &&
          packetLoss == other.packetLoss &&
          nodeName == other.nodeName;
}
