// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 按 exe 名或窗口标题过滤进程，并列出其 UDP 口。
Future<List<GameProcessInfo>> listGameProcesses({
  required List<String> exeNames,
  required List<String> windowNeedles,
}) => RustLib.instance.api.crateApiProcessListGameProcesses(
  exeNames: exeNames,
  windowNeedles: windowNeedles,
);

class GameProcessInfo {
  final int pid;
  final String exe;
  final String title;
  final String path;
  final Uint16List udpPorts;

  const GameProcessInfo({
    required this.pid,
    required this.exe,
    required this.title,
    required this.path,
    required this.udpPorts,
  });

  @override
  int get hashCode =>
      pid.hashCode ^
      exe.hashCode ^
      title.hashCode ^
      path.hashCode ^
      udpPorts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameProcessInfo &&
          runtimeType == other.runtimeType &&
          pid == other.pid &&
          exe == other.exe &&
          title == other.title &&
          path == other.path &&
          udpPorts == other.udpPorts;
}
